name: withdrawal-manager-queue
version: 1.0.0
source: contracts
packages:
  - path: contracts/MapleWithdrawalManager.sol
    contractName: MapleWithdrawalManager
customDescription: Withdrawal Manager Queue Artifacts and ABIs
